/// Flutter icons AppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData call_end = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speaker_off = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_off = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_off = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_single = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData owner = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emoji_surprise = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData select = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mark_unread = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData member_add = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audio = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headset = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_circle = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headphone = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reaction = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData letter = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_member = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dm = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData private_channel = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData channel = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
